### ISSUE TITLE
Feat(java): Update all Lambda functions to Java 21

### ISSUE THREAD

**Issue by saragerion** [aws-samples/powertools-for-aws-lambda-workshop#44]
The deployment process for the Java application is impacted by a CDK nag error:

> AwsSolutions-L1
> The non-container Lambda function is not configured to use the latest runtime version.
> Use the latest available runtime for the targeted language to avoid technical debt. Runtimes specific to a language or framework version are deprecated when the version reaches end of life. This rule only applies to non-container Lambda functions.

<img width="1440" alt="Screenshot 2024-02-29 at 20 05 42" src="https://github.com/aws-samples/powertools-for-aws-lambda-workshop/assets/47529391/63099c74-cf3e-4fdf-a8b6-40f90edc0b99">

Solution: update of runtimes to use java version 21.

**Comment by dreamorosi** [comment]
Runtime version update merged in PR #45. Thank you!
